import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { headers } from 'next/headers'
import type { Metadata } from 'next'
import { QueryProvider } from '@/modules/shared/contexts/query'
import { Web3Provider } from '@/modules/shared/contexts/web3'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const rqHeaders = await headers()
  const cookies = rqHeaders.get('cookie')

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Web3Provider cookies={cookies}>
          <QueryProvider>{children}</QueryProvider>
        </Web3Provider>
      </body>
    </html>
  )
}
